package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}
			g := plugin.NewGeneratedFile(f.GeneratedFilenamePrefix+"_fiber.pb.go", f.GoImportPath)
			g.P("// Code generated by protoc-gen-fiber. DO NOT EDIT.")
			g.P("package ", f.GoPackageName)
			g.P()
			g.P("// TODO: generate Fiber routes here")
		}
		return nil
	})
}
